### ISSUE TITLE
WHY ???  ImportError: No module named 'NetScan'

### ISSUE THREAD

**Issue by jibanli** [niloofarkheirkhah/nili#5]
ss@ss-VirtualBox:~/nili$ nili
Warning: FastBinaryTree not available, using Python version BinaryTree.
Warning: FastAVLTree not available, using Python version AVLTree.
Warning: FastRBTree not available, using Python version RBTree.
Traceback (most recent call last):
  File "/usr/local/bin/nili", line 11, in <module>
    load_entry_point('nili==0.1.1', 'console_scripts', 'nili')()
  File "/home/ss/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ss/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/ss/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/ss/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/nili/__main__.py", line 4, in <module>
    import NetScan
ImportError: No module named 'NetScan'

**Comment by StephenHaruna** [comment]
any updates on this issue?
